#!/usr/bin/env bash
#
# update-completions - Update Zsh completion scripts for various tools.
#

#  Mark dir if it doesnt exist, if it does, clear contents
mkdir -p $ZSH_COMPLETIONS_DIR
rm $ZSH_COMPLETIONS_DIR/*

pitchfork completion zsh > $ZSH_COMPLETIONS_DIR/_pitchfork
opencode completion > $ZSH_COMPLETIONS_DIR/_opencode
op completion zsh > $ZSH_COMPLETIONS_DIR/_op
npm completion zsh > $ZSH_COMPLETIONS_DIR/_npm
pnpm completion zsh > $ZSH_COMPLETIONS_DIR/_pnpm
node --completion-bash > $ZSH_COMPLETIONS_DIR/_node

# Download file and move to completions dir
curl -o $ZSH_COMPLETIONS_DIR/_cowsay https://raw.githubusercontent.com/zsh-users/zsh/4f95c6defd308d8ef10247640c722b9d08953ff7/Completion/Unix/Command/_cowsay
