#!/usr/bin/env bash
#
# cdpr - cd to project root, defined as the top-level of the git repository.
#

if ! git rev-parse --is-inside-work-tree &>/dev/null; then
  echo "cdpr: Cannot cd to project root. \$PWD not in a git project."
  return 1
fi
cd "$(git rev-parse --show-toplevel)"
