#!/bin/zsh
function update_git_completions {
  emulate -L zsh
  # Download the git scripts
  echo "Generating git completions..."
  local giturl=https://raw.githubusercontent.com/git/git/master/contrib/completion
  local dest=${1:-$ZSH_COMPLETIONS_DIR}
  [[ -d $dest ]] || mkdir -p $dest
  curl -fsSL $giturl/git-completion.bash -o $dest/git-completion.bash
  curl -fsSL $giturl/git-completion.zsh -o $dest/_git
}
update_git_completions "$@"
