#!/usr/bin/env zsh

#  Mark dir if it doesnt exist, if it does, clear contents
mkdir -p $ZSH_COMPLETIONS_DIR
rm $ZSH_COMPLETIONS_DIR/*

pitchfork completion zsh > $ZSH_COMPLETIONS_DIR/_pitchfork
opencode completion > $ZSH_COMPLETIONS_DIR/_opencode
op completion zsh > $ZSH_COMPLETIONS_DIR/_op
npm completion zsh > $ZSH_COMPLETIONS_DIR/_npm
pnpm completion zsh > $ZSH_COMPLETIONS_DIR/_pnpm
node --completion-bash > $ZSH_COMPLETIONS_DIR/_node
